version: '3.8'

services:
  db:
    image: postgres:17
    container_name: feshop_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    
  api:
    image: feshop_api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feshop_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5555:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  postgres_data:    